# Site settings
title: Lin Man
description: Software Engineer
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
short_name: LM
username: Lin Man
user_description: I want to be more than just a coder.
user_title: Software Engineer
user_title_cn: 高级前端开发工程师
email: 591858556@qq.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ["package.json", "src", "node_modules"]

posts:
  - title:'使用docker打包安卓APP'
    url:'/2020-07-05-build-app'
  - title:'快速释放docker空间的脚本'
    url:'2020-07-08-script-1'
