# Site settings
title: Lin Man
description: Software Engineer
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
short_name: LM
username: Lin Man
user_description: I want to be more than just a coder.
user_title: Software Engineer
user_title_cn: 高级前端开发工程师
email: 591858556@qq.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

baseurl: https://manman0310.github.io
github_url: https://manman0310.github.io/lm

exclude: ["package.json", "src", "node_modules"]

posts:
  - title:'使用docker打包安卓APP'
    url:'lm/2020-07-05-build-app'
  - title:'快速释放docker空间的脚本'
    url:'lm/2020-07-08-script-1'
  - title:'基于cordova自动打包app脚本'
    url:'lm/2020-08-17-auto-build-app-shell'
  - title:'常用命令备忘录'
    url:'lm/2020-07-20-memo-script'
  - title:'基于cordova的安卓APP基础镜像'
    url:'lm/2020-08-18-app-base-dockerfile'
