# Site settings
title: Lin Man
description: Software Engineer & PM
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
short_name: LM
username: 林 漫
user_description: 懂开发的产品 & 项目经理
user_title: Product Manager & Project Manager
user_title_cn: 产品 & 项目经理
email: 591858556@qq.com
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
baseurl: https://manman0310.github.io
github_url: https://manman0310.github.io/lm

exclude: ["package.json", "src", "node_modules"]

select_top: all

